#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

num1 = 1
num2 = 1
num3 = 0
maximum = 4000000
puts num1
while num1 < maximum && num2 < maximum
  #Add previous number to current number
  num1 += num2

  #Add the new number to the sum if it's even and below max
  #Output the number to see what's going on, if it's even and below max
  num3 += num1 if num1 % 2 == 0 && num1 < maximum
  puts num1 if num1 % 2 == 0 && num1 < maximum

  #Add previous number to current number
  num2 += num1

  #Add the new number to sum if it's even and below max
  #Output the number to see what's going on, if it's even and below max
  num3 +=num2 if num2 % 2 == 0 && num2 < maximum
  puts num2 if num2 % 2 == 0 && num2 < maximum
end
print "The sum of the even previous numbers is: ", num3
